rvm: 1.9.3
language: objective-c
before_script:
  - export LANG=en_US.UTF-8
  - gem install xcpretty
  - gem install cocoapods -v '0.29.0'
script: xcodebuild -workspace IGHTMLQuery.xcworkspace -scheme IGHTMLQuery -sdk iphonesimulator test | xcpretty -c; exit ${PIPESTATUS[0]}
